language: cpp
dist: trusty
compiler:
  - gcc
os:
  - linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

#script:
#  - make
#  - build/lexer

script:
  - mkdir build
  - pushd build
  - CC=gcc-9 CXX=g++-9 cmake ..
  - make VERBOSE=1
  # Todo: export these test results
  - ASAN_OPTIONS=detect_leaks=0 ./tests --gtest_output=xml:"tests.xml"
  - popd
