language: cpp
dist: xenial
compiler:
  - gcc
os:
  - linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - re2c
      - kcov

#script:
#  - make
#  - build/lexer

script:
  - mkdir build
  - pushd build
  - CC=gcc-9 CXX=g++-9 cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1
  # Todo: export these test results
  - kcov --coveralls-id=$TRAVIS_JOB_ID --include-pattern='Meter/Source' ./out tests --gtest_output=xml:"tests.xml"
  - popd
